---
name: Auto-deployment of ucs_containers Documentation
on:
  push:
    branches: [main]

env:
  ENV_FILE: custom.env

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0  # otherwise, you will failed to push refs to dest repo

      - name: Set up Python 3.
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Poetry.
        uses: snok/install-poetry@v1.3

      - name: Install dependencies.
        run: poetry install -E docs

      - name: Import environment variables from file
        id: import-env
        shell: bash
        run: |
          touch ${ENV_FILE}  # incase missing
          while read line; do
            echo "$line" >> $GITHUB_ENV
          done < ${ENV_FILE}

      - name: Build documentation.
        run: |
          mkdir -p docs
          touch docs/.nojekyll
          poetry run gen-doc ${LINKML_GENERATORS_DOC_ARGS} -d docs src/ucs_containers/schema/ucs_containers.yaml
          ([ ! -f docs/about.md ] && cp src/docs/about.md docs/) || true
          poetry run mkdocs gh-deploy
